/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         newName: "your_group_name"
 *     }
 */
export interface GroupUpdateRequest {
    /** The new name of the group being renamed. */
    newName: string;
}
