/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WebsiteCrawlRequestWebsitesItem {
    /** the bucketId of the bucket which this website will be ingested to. */
    bucketId: number;
    /** The maximum number of pages to crawl */
    cap?: number;
    /** The maximum depth of linked pages to follow from the sourceUrl */
    depth?: number;
    /** Custom metadata which can be used to influence GroundX's search functionality. This data can be used to further hone GroundX search. */
    searchData?: Record<string, unknown>;
    /** The URL from which the crawl is initiated. */
    sourceUrl: string;
}
