// This file was auto-generated by Fern from our API Definition.

export interface ApiKeyDetail {
    /** The GroundX API key */
    apiKey: string;
    /** The data time when the API key was created, in RFC3339 format */
    created?: string;
    name?: string;
}
