// This file was auto-generated by Fern from our API Definition.

export interface BucketDetail {
    bucketId: number;
    /** The data time when the bucket was created, in RFC3339 format */
    created?: string | undefined;
    /** The number of files contained in the content bucket */
    fileCount?: number | undefined;
    /** The total file size of files contained in the content bucket */
    fileSize?: string | undefined;
    name?: string | undefined;
    /** The data time when the bucket was last updated, in RFC3339 format */
    updated?: string | undefined;
}
