/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BucketDetail {
    bucketId: number;
    /** The data time when the bucket was created, in RFC3339 format */
    created?: string;
    /** The number of files contained in the content bucket */
    fileCount?: number;
    /** The total file size of files contained in the content bucket */
    fileSize?: string;
    name?: string;
    /** The data time when the bucket was last updated, in RFC3339 format */
    updated?: string;
}
