/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../index.js";

export interface BucketListResponse {
    buckets?: GroundX.BucketDetail[];
    /** The number of buckets returned in the current response */
    count?: number;
    /** The number of buckets that have not been returned yet, will be null if there are no remaining buckets */
    remaining?: number;
    /** The total number of buckets found */
    total?: number;
}
