// This file was auto-generated by Fern from our API Definition.

/**
 * Public custom leaf-field metadata used for route integrity and executable-step field-count validation.
 */
export interface CustomWorkflowLeafField {
    /** RFC 6901 JSON Pointer to the prompted final schema leaf. Repeated item paths use a literal * segment and count once per prompted schema leaf. */
    finalPath: string;
    workflowGroup: string;
    workflowField: string;
    stepName: string;
    level: CustomWorkflowLeafField.Level;
    outputKey: string;
    /** Final schema field type for this prompted leaf. */
    fieldType: string;
    /** Whether this leaf belongs to a repeated/list field definition. */
    isRepeated: boolean;
    /** none is valid only for non-repeated leaves; field counts a repeated value as one prompted leaf; item uses literal * path segments for prompted item leaves. */
    repetitionScope: CustomWorkflowLeafField.RepetitionScope;
}

export namespace CustomWorkflowLeafField {
    export const Level = {
        Chunk: "chunk",
        Section: "section",
        Document: "document",
    } as const;
    export type Level = (typeof Level)[keyof typeof Level];
    /** none is valid only for non-repeated leaves; field counts a repeated value as one prompted leaf; item uses literal * path segments for prompted item leaves. */
    export const RepetitionScope = {
        None: "none",
        Field: "field",
        Item: "item",
    } as const;
    export type RepetitionScope = (typeof RepetitionScope)[keyof typeof RepetitionScope];
}
