// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

/**
 * Account information for the user
 */
export interface CustomerDetail {
    /** Email associated with the account */
    email?: string | undefined;
    /** Given name associated with the account, if known */
    first?: string | undefined;
    /** Family name associated with the account, if known */
    last?: string | undefined;
    /** Account status associated with the customer, if known */
    status?: CustomerDetail.Status | undefined;
    subscription?: GroundX.SubscriptionDetail | undefined;
}

export namespace CustomerDetail {
    /** Account status associated with the customer, if known */
    export const Status = {
        Admin: "admin",
        ApiKey: "apiKey",
        Archived: "archived",
        Invalid: "invalid",
        PartnerApiKey: "partnerApiKey",
        PartnerModUser: "partnerModUser",
        Partner: "partner",
        Test: "test",
        User: "user",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
