// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

/**
 * Element-level custom workflow step config. It supports existing prompt, engine, and include settings; fixed-output field is omitted because custom output routing is defined by outputRoutes and leafFields.
 */
export interface CustomWorkflowStepElementConfig {
    engine?: GroundX.WorkflowEngine | undefined;
    includes?: Record<string, boolean> | undefined;
    /** Prompt group for this custom step element config. On workflow update, omit prompt or send an empty object to use the default prompt group, send an object to customize supplied prompt members, and send null to use no prompt group. */
    prompt?: GroundX.WorkflowPromptGroup | undefined;
}
