// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

/**
 * Account information for the user
 */
export interface CustomerDetail {
    /** Email associated with the account */
    email?: string | undefined;
    /** Given name associated with the account, if known */
    first?: string | undefined;
    /** Family name associated with the account, if known */
    last?: string | undefined;
    subscription?: GroundX.SubscriptionDetail | undefined;
}
