// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

export interface CustomerUsageResponse {
    customer: CustomerUsageResponse.Customer;
}

export namespace CustomerUsageResponse {
    export interface Customer {
        usage: GroundX.CustomerUsageDetail;
    }
}
