// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

/**
 * Custom workflow step config keyed by element type. Element configs omit fixed-output field; custom output storage is derived from level, kind, outputRoutes, and leafFields.
 */
export interface CustomWorkflowStepConfig {
    all?: GroundX.CustomWorkflowStepElementConfig | undefined;
    figure?: GroundX.CustomWorkflowStepElementConfig | undefined;
    json?: GroundX.CustomWorkflowStepElementConfig | undefined;
    paragraph?: GroundX.CustomWorkflowStepElementConfig | undefined;
    table?: GroundX.CustomWorkflowStepElementConfig | undefined;
    "table-figure"?: GroundX.CustomWorkflowStepElementConfig | undefined;
}
