/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../index.js";

export interface DocumentListResponse {
    documents?: GroundX.DocumentDetail[];
    nextToken?: string;
}
