/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../index";

export interface DocumentDetail {
    bucketId?: number;
    /** Unique system generated ID for the document */
    documentId: string;
    fileName?: string;
    /** The file size of the file stored in GroundX */
    fileSize?: string;
    fileType?: GroundX.DocumentType;
    /** Unique system generated ID for the ingest request */
    processId?: string;
    searchData?: Record<string, unknown>;
    /** Source document URL */
    sourceUrl?: string;
    status?: GroundX.ProcessingStatus;
    statusMessage?: string;
    /** Document X-Ray results */
    xrayUrl?: string;
}
