/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../index.js";

export interface DocumentLookupResponse {
    /** The number of results returned in the current response */
    count?: number;
    documents?: GroundX.DocumentDetail[];
    nextToken?: string;
    /** The number of results that have not been returned yet. Will be null if there are no remaining results. */
    remaining?: number;
    /** The total number of results found */
    total?: number;
}
