// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

/**
 * Document X-Ray data. Custom outputs are exposed through level-specific maps and fixed legacy fields remain additive.
 */
export interface DocumentXray {
    chunks?: GroundX.DocumentXrayChunk[] | undefined;
    customDocumentOutputs?: GroundX.CustomWorkflowOutputMap | undefined;
    documentPages?: GroundX.DocumentXrayPage[] | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
