// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

/**
 * X-Ray page data, including page-local chunks when returned by the runtime.
 */
export interface DocumentXrayPage {
    chunks?: GroundX.DocumentXrayChunk[] | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
