// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

export interface DocumentListResponse {
    documents?: GroundX.DocumentDetail[] | undefined;
    nextToken?: string | undefined;
}
