// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

/**
 * X-Ray chunk data. Known custom output maps are typed while legacy and system-generated fields remain additive.
 */
export interface DocumentXrayChunk {
    customChunkOutputs?: GroundX.CustomWorkflowOutputMap | undefined;
    customSectionOutputs?: GroundX.CustomWorkflowOutputMap | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
