// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

export interface GroupDetail {
    /** The content buckets associated with the group */
    buckets?: GroundX.BucketDetail[] | undefined;
    /** The data time when the group was created, in RFC3339 format */
    created?: string | undefined;
    /** The number of files contained in the content buckets associated with the group */
    fileCount?: number | undefined;
    /** The total file size of files contained in the content buckets associated with the group */
    fileSize?: string | undefined;
    groupId: number;
    name?: string | undefined;
    /** The data time when the group was last updated, in RFC3339 format */
    updated?: string | undefined;
}
