// This file was auto-generated by Fern from our API Definition.

export interface HealthService {
    /** The data time when the service status was last updated, in RFC3339 format */
    lastUpdate: string;
    /** The name of the service */
    service: string;
    /** The health status of the service */
    status: HealthService.Status;
}

export namespace HealthService {
    /** The health status of the service */
    export const Status = {
        Healthy: "healthy",
        Degraded: "degraded",
        Down: "down",
        Unknown: "unknown",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
