/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../index.js";

export interface HealthResponse {
    health: HealthResponse.Health;
}

export namespace HealthResponse {
    export interface Health {
        services: GroundX.HealthService[];
    }
}
