/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../index";

export interface HealthService {
    /** The data time when the service status was last updated, in RFC3339 format */
    lastUpdate: string;
    /** The name of the service */
    service: string;
    /** The health status of the service */
    status: GroundX.HealthServiceStatus;
}
