/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../index.js";

export interface IngestStatus {
    id?: number;
    processId: string;
    progress?: IngestStatus.Progress;
    status: GroundX.ProcessingStatus;
    statusMessage?: string;
}

export namespace IngestStatus {
    export interface Progress {
        cancelled?: Progress.Cancelled;
        complete?: Progress.Complete;
        errors?: Progress.Errors;
        processing?: Progress.Processing;
    }

    export namespace Progress {
        export interface Cancelled {
            documents?: GroundX.DocumentDetail[];
            total?: number;
        }

        export interface Complete {
            documents?: GroundX.DocumentDetail[];
            total?: number;
        }

        export interface Errors {
            documents?: GroundX.DocumentDetail[];
            total?: number;
        }

        export interface Processing {
            documents?: GroundX.DocumentDetail[];
            total?: number;
        }
    }
}
