/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as EyeLevel from "../index";

export interface IngestResponseIngest {
    processId: string;
    status: EyeLevel.ProcessingStatus;
}
