/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../index";

export interface IngestResponseIngest {
    processId: string;
    status: GroundX.ProcessingStatus;
}
