// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

export interface IngestStatus {
    id?: number | undefined;
    processId: string;
    progress?: IngestStatus.Progress | undefined;
    status: GroundX.ProcessingStatus;
    statusMessage?: string | undefined;
}

export namespace IngestStatus {
    export interface Progress {
        cancelled?: Progress.Cancelled | undefined;
        complete?: Progress.Complete | undefined;
        errors?: Progress.Errors | undefined;
        processing?: Progress.Processing | undefined;
        queued?: Progress.Queued | undefined;
    }

    export namespace Progress {
        export interface Cancelled {
            documents?: GroundX.DocumentDetail[] | undefined;
            total?: number | undefined;
        }

        export interface Complete {
            documents?: GroundX.DocumentDetail[] | undefined;
            total?: number | undefined;
        }

        export interface Errors {
            documents?: GroundX.DocumentDetail[] | undefined;
            total?: number | undefined;
        }

        export interface Processing {
            documents?: GroundX.DocumentDetail[] | undefined;
            total?: number | undefined;
        }

        export interface Queued {
            documents?: GroundX.DocumentDetail[] | undefined;
            total?: number | undefined;
        }
    }
}
