// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

export interface IngestLocalDocument {
    /** The binary file data being ingested. */
    blob: string;
    metadata: GroundX.IngestLocalDocumentMetadata;
}
