/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Current usage and limits for the user for the given metric
 */
export interface MeterDetail {
    /** Maximum limit for the current billing period */
    max?: number;
    /** Unique system generated ID for the meteric */
    meterId?: string;
    /** Current usage for the current billing period */
    value?: number;
}
