/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as EyeLevel from "../index";

export interface ProcessStatusResponseIngestProgressCancelled {
    documents?: EyeLevel.DocumentDetail[];
    total?: number;
}
