/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ProcessingStatus = "queued" | "processing" | "error" | "complete" | "cancelled" | "active" | "inactive";
export const ProcessingStatus = {
    Queued: "queued",
    Processing: "processing",
    Error: "error",
    Complete: "complete",
    Cancelled: "cancelled",
    Active: "active",
    Inactive: "inactive",
} as const;
