// This file was auto-generated by Fern from our API Definition.

/** The amount of processing of document chunks to perform. 'none' specifies the document to go through only text extraction and chunking. Documents uploaded with 'full' go through text extraction, chunking, and an agentic process that creates robust metadata for each chunk. (default 'full'). */
export const ProcessLevel = {
    None: "none",
    Full: "full",
} as const;
export type ProcessLevel = (typeof ProcessLevel)[keyof typeof ProcessLevel];
