// This file was auto-generated by Fern from our API Definition.

export const ProcessingStatus = {
    Queued: "queued",
    Processing: "processing",
    Error: "error",
    Complete: "complete",
    Cancelled: "cancelled",
    Active: "active",
    Inactive: "inactive",
} as const;
export type ProcessingStatus = (typeof ProcessingStatus)[keyof typeof ProcessingStatus];
