/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as EyeLevel from "../index";

export interface ProcessStatusResponseIngestProgress {
    cancelled?: EyeLevel.ProcessStatusResponseIngestProgressCancelled;
    complete?: EyeLevel.ProcessStatusResponseIngestProgressComplete;
    errors?: EyeLevel.ProcessStatusResponseIngestProgressErrors;
    processing?: EyeLevel.ProcessStatusResponseIngestProgressProcessing;
}
