/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../index";

export interface ProcessStatusResponseIngestProgressComplete {
    documents?: GroundX.DocumentDetail[];
    total?: number;
}
