/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The amount of processing of document chunks to perform (default 'full')
 */
export type ProcessLevel = "none" | "full";
export const ProcessLevel = {
    None: "none",
    Full: "full",
} as const;
