/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ProcessingStatus = "queued" | "processing" | "error" | "complete" | "cancelled";

export const ProcessingStatus = {
    Queued: "queued",
    Processing: "processing",
    Error: "error",
    Complete: "complete",
    Cancelled: "cancelled",
} as const;
