// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

export interface SearchResponse {
    search: SearchResponse.Search;
}

export namespace SearchResponse {
    export interface Search {
        /** Total results */
        count?: number | undefined;
        /** Search results */
        results?: GroundX.SearchResultItem[] | undefined;
        /** The original search request query */
        query?: string | undefined;
        /** Confidence score in the search results */
        score?: number | undefined;
        /** The actual search query, if the search request query was re-written */
        searchQuery?: string | undefined;
        /** Suggested context for LLM completion */
        text?: string | undefined;
        /** For paginated results */
        nextToken?: string | undefined;
    }
}
