// This file was auto-generated by Fern from our API Definition.

/** The attribute to use to sort results */
export const Sort = {
    Name: "name",
    Created: "created",
} as const;
export type Sort = (typeof Sort)[keyof typeof Sort];
