/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The order in which to sort results
 */
export type SortOrder = "asc" | "desc";

export const SortOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
