/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as EyeLevel from "../index";

export interface SubscriptionDetailMeters {
    fileTokens?: EyeLevel.MeterDetail;
    searches?: EyeLevel.MeterDetail;
}
