/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../index";

export interface SubscriptionDetailMeters {
    fileTokens?: GroundX.MeterDetail;
    searches?: GroundX.MeterDetail;
}
