// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

/**
 * Subscription information for the user, including current usage and limits
 */
export interface SubscriptionDetail {
    meters?: SubscriptionDetail.Meters;
}

export namespace SubscriptionDetail {
    export interface Meters {
        fileTokens?: GroundX.MeterDetail;
        searches?: GroundX.MeterDetail;
    }
}
