/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../index.js";

/**
 * A collection of workflow steps
 */
export interface WorkflowSteps {
    "chunk-instruct"?: WorkflowSteps.ChunkInstruct;
    "chunk-summary"?: WorkflowSteps.ChunkSummary;
    "doc-keys"?: WorkflowSteps.DocKeys;
    "doc-summary"?: WorkflowSteps.DocSummary;
    "search-query"?: WorkflowSteps.SearchQuery;
    "sect-instruct"?: WorkflowSteps.SectInstruct;
    "sect-summary"?: WorkflowSteps.SectSummary;
}

export namespace WorkflowSteps {
    export interface ChunkInstruct {
        figure?: GroundX.WorkflowStep;
        json?: GroundX.WorkflowStep;
        "table-figure"?: GroundX.WorkflowStep;
    }

    export interface ChunkSummary {
        all?: GroundX.WorkflowStep;
        figure?: GroundX.WorkflowStep;
        json?: GroundX.WorkflowStep;
        table?: GroundX.WorkflowStep;
        "table-figure"?: GroundX.WorkflowStep;
    }

    export interface DocKeys {
        all?: GroundX.WorkflowStep;
    }

    export interface DocSummary {
        all?: GroundX.WorkflowStep;
        json?: GroundX.WorkflowStep;
    }

    export interface SearchQuery {
        all?: GroundX.WorkflowStep;
    }

    export interface SectInstruct {
        table?: GroundX.WorkflowStep;
    }

    export interface SectSummary {
        all?: GroundX.WorkflowStep;
        table?: GroundX.WorkflowStep;
    }
}
