// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

export interface WorkflowRequest {
    chunkStrategy?: WorkflowRequest.ChunkStrategy | undefined;
    /** The name of the workflow being created. */
    name?: string | undefined;
    /** Workflow YAML. GroundX validates it and creates the workflow settings. When yaml is supplied, omit extract, customSteps, outputRoutes, leafFields, and steps. A v1 workflow declares extraction_policy_version, workflow.custom_steps, workflow.agent_chain, a workflow_step and role for each group, and a workflow_output_key for each routed field. repeats: true declares an array of records; unique_attrs names fields used to identify the same record. For related lists, match_attrs names the shared fields and passthrough.from names the parent group. String matching ignores capitalization and surrounding whitespace. Blank or missing values do not match. When several parents match, GroundX uses the first. Group names and workflow_output_key values become output names. */
    yaml?: string | undefined;
    /** Extract agent definitions. */
    extract?: Record<string, unknown> | undefined;
    template?: GroundX.WorkflowTemplate | undefined;
    sectionStrategy?: WorkflowRequest.SectionStrategy | undefined;
    steps?: GroundX.WorkflowSteps | undefined;
    /** Workflow-level custom extraction steps. Legacy fixed steps remain under steps. */
    customSteps?: GroundX.CustomWorkflowStep[] | undefined;
    /** Custom output routes. Each record must have exactly one matching leafFields record on finalPath, workflowGroup, workflowField, stepName, level, and outputKey. */
    outputRoutes?: GroundX.CustomWorkflowOutputRoute[] | undefined;
    /** Custom leaf-field metadata used to validate route integrity and executable-step field counts. */
    leafFields?: GroundX.CustomWorkflowLeafField[] | undefined;
}

export namespace WorkflowRequest {
    export const ChunkStrategy = {
        Element: "element",
        Size: "size",
    } as const;
    export type ChunkStrategy = (typeof ChunkStrategy)[keyof typeof ChunkStrategy];
    export const SectionStrategy = {
        Chunks: "chunks",
        Page: "page",
    } as const;
    export type SectionStrategy = (typeof SectionStrategy)[keyof typeof SectionStrategy];
}
