// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

/**
 * Configurations for an agent, including LLM information and prompts
 */
export interface WorkflowStep {
    all?: GroundX.WorkflowStepConfig;
    figure?: GroundX.WorkflowStepConfig;
    json?: GroundX.WorkflowStepConfig;
    paragraph?: GroundX.WorkflowStepConfig;
    table?: GroundX.WorkflowStepConfig;
    "table-figure"?: GroundX.WorkflowStepConfig;
}
