// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

/**
 * Configurations for an agent, including LLM information and prompts
 */
export interface WorkflowStepConfig {
    engine?: GroundX.WorkflowEngine | undefined;
    /** The field where agent output will be saved */
    field?: WorkflowStepConfig.Field | undefined;
    includes?: Record<string, boolean> | undefined;
    prompt?: GroundX.WorkflowPromptGroup | undefined;
}

export namespace WorkflowStepConfig {
    /** The field where agent output will be saved */
    export const Field = {
        DocSum: "doc-sum",
        DocKeys: "doc-keys",
        SectSum: "sect-sum",
        SectKeys: "sect-keys",
        ChunkSum: "chunk-sum",
        ChunkKeys: "chunk-keys",
        ChunkInstruct: "chunk-instruct",
        Text: "text",
    } as const;
    export type Field = (typeof Field)[keyof typeof Field];
}
