// This file was auto-generated by Fern from our API Definition.

/**
 * Configurations for the prompt an agent uses in a workflow
 */
export interface WorkflowPrompt {
    /** A short version of the prompt that is included in historical chat transcripts as part of the prompt context */
    abbreviated?: string;
    /** The prompt that is sent to the LLM */
    prompt?: string;
    /** An enumerated value that conforms to OpenAI '/chat/completion' specifications */
    role?: WorkflowPrompt.Role;
}

export namespace WorkflowPrompt {
    /** An enumerated value that conforms to OpenAI '/chat/completion' specifications */
    export const Role = {
        Assistant: "assistant",
        Developer: "developer",
        System: "system",
        User: "user",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
