// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

/**
 * A collection of workflow steps
 */
export interface WorkflowSteps {
    "chunk-instruct"?: GroundX.WorkflowStep;
    "chunk-keys"?: GroundX.WorkflowStep;
    "chunk-summary"?: GroundX.WorkflowStep;
    "doc-keys"?: GroundX.WorkflowStep;
    "doc-summary"?: GroundX.WorkflowStep;
    "search-query"?: GroundX.WorkflowStep;
    "sect-instruct"?: GroundX.WorkflowStep;
    "sect-keys"?: GroundX.WorkflowStep;
    "sect-summary"?: GroundX.WorkflowStep;
}
