// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

export interface WorkflowRequest {
    chunkStrategy?: WorkflowRequest.ChunkStrategy | undefined;
    /** The name of the workflow being created. */
    name?: string | undefined;
    /** Extract agent definitions. */
    extract?: Record<string, unknown> | undefined;
    sectionStrategy?: WorkflowRequest.SectionStrategy | undefined;
    steps?: GroundX.WorkflowSteps | undefined;
}

export namespace WorkflowRequest {
    export const ChunkStrategy = {
        Element: "element",
        Size: "size",
    } as const;
    export type ChunkStrategy = (typeof ChunkStrategy)[keyof typeof ChunkStrategy];
    export const SectionStrategy = {
        Chunks: "chunks",
        Page: "page",
    } as const;
    export type SectionStrategy = (typeof SectionStrategy)[keyof typeof SectionStrategy];
}
