// This file was auto-generated by Fern from our API Definition.

/**
 * Workflow-level prompt template values used by fixed and custom workflow step prompts.
 */
export type WorkflowTemplate = Record<string, string>;
