// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

/**
 * Workflow information
 */
export interface WorkflowDetail {
    chunkStrategy?: WorkflowDetail.ChunkStrategy | undefined;
    /** The documentId associated with the workflow */
    documentId?: string | undefined;
    /** The bucketId or groupId associated with the workflow */
    id?: number | undefined;
    /** The human-readable name of the workflow */
    name?: string | undefined;
    /** Extract agent definitions. */
    extract?: Record<string, unknown> | undefined;
    sectionStrategy?: WorkflowDetail.SectionStrategy | undefined;
    steps?: GroundX.WorkflowSteps | undefined;
    /** Information describing what the workflow is associated with */
    relationships?: WorkflowDetail.Relationships | undefined;
    /** Unique system generated ID for the workflow */
    workflowId?: string | undefined;
}

export namespace WorkflowDetail {
    export const ChunkStrategy = {
        Element: "element",
        Size: "size",
    } as const;
    export type ChunkStrategy = (typeof ChunkStrategy)[keyof typeof ChunkStrategy];
    export const SectionStrategy = {
        Chunks: "chunks",
        Page: "page",
    } as const;
    export type SectionStrategy = (typeof SectionStrategy)[keyof typeof SectionStrategy];

    /**
     * Information describing what the workflow is associated with
     */
    export interface Relationships {
        /** A boolean indicating whether the workflow is associated with the account */
        account?: boolean | undefined;
        /** An array of documentIds associated with the workflow */
        documents?: string[] | undefined;
        /** An array of bucketIds or groupIds associated with the workflow */
        ids?: number[] | undefined;
    }
}
