// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../index.js";

/**
 * Configurations for an agent, including LLM information and prompts
 */
export interface WorkflowStep {
    engine?: GroundX.WorkflowEngine;
    prompt?: GroundX.WorkflowPromptGroup;
}
