// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         n: 1,
 *         nextToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9",
 *         verbosity: 1,
 *         query: "my search query"
 *     }
 */
export interface SearchRequest {
    /** The maximum number of returned search results. Accepts 1-100 with a default of 20. */
    n?: number;
    /** A token for pagination. If the number of search results for a given query is larger than n, the response will include a "nextToken" value. That token can be included in this field to retrieve the next batch of n search results. */
    nextToken?: string;
    /** The amount of data returned with each search result. 0 == no search results, only the recommended context. 1 == search results but no searchData. 2 == search results and searchData. */
    verbosity?: number;
    /** The search query to be used to find relevant documentation. */
    query: string;
    /** A dictionary of key-value pairs that can be used to pre-filter documents prior to a search. */
    filter?: Record<string, unknown>;
    /** The minimum search relevance score required to include the result. By default, this is 10.0. */
    relevance?: number;
}
