// This file was auto-generated by Fern from our API Definition.

import * as GroundX from "../../src/api/index";
import { GroundXClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ApiKeyClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { apiKeys: [{ apiKey: "apiKey", created: "2023-10-03T08:59:39Z", name: "name" }] };
        server.mockEndpoint().get("/v1/apikey").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.apiKey.list();
        expect(response).toEqual({
            apiKeys: [
                {
                    apiKey: "apiKey",
                    created: "2023-10-03T08:59:39Z",
                    name: "name",
                },
            ],
        });
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "your_apikey_name" };
        const rawResponseBody = { apiKeys: [{ apiKey: "apiKey", created: "2023-10-03T08:59:39Z", name: "name" }] };
        server
            .mockEndpoint()
            .post("/v1/apikey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.apiKey.create({
            name: "your_apikey_name",
        });
        expect(response).toEqual({
            apiKeys: [
                {
                    apiKey: "apiKey",
                    created: "2023-10-03T08:59:39Z",
                    name: "name",
                },
            ],
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/apikey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKey.create({
                name: "name",
            });
        }).rejects.toThrow(GroundX.BadRequestError);
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "your_apikey_name" };
        const rawResponseBody = { apiKeys: [{ apiKey: "apiKey", created: "2023-10-03T08:59:39Z", name: "name" }] };
        server
            .mockEndpoint()
            .put("/v1/apikey/apiKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.apiKey.update("apiKey", {
            name: "your_apikey_name",
        });
        expect(response).toEqual({
            apiKeys: [
                {
                    apiKey: "apiKey",
                    created: "2023-10-03T08:59:39Z",
                    name: "name",
                },
            ],
        });
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "OK" };
        server
            .mockEndpoint()
            .delete("/v1/apikey/apiKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.apiKey.delete("apiKey");
        expect(response).toEqual({
            message: "OK",
        });
    });
});
