// This file was auto-generated by Fern from our API Definition.

import * as GroundX from "../../src/api/index";
import { GroundXClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Buckets", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            buckets: [
                {
                    bucketId: 1,
                    created: "2023-10-03T08:59:39Z",
                    fileCount: 1,
                    fileSize: "3.1GB",
                    name: "name",
                    updated: "2023-10-03T08:59:39Z",
                },
            ],
            count: 1,
            remaining: 10,
            total: 30,
        };
        server.mockEndpoint().get("/v1/bucket").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.buckets.list({
            n: 1,
            nextToken: "nextToken",
        });
        expect(response).toEqual({
            buckets: [
                {
                    bucketId: 1,
                    created: "2023-10-03T08:59:39Z",
                    fileCount: 1,
                    fileSize: "3.1GB",
                    name: "name",
                    updated: "2023-10-03T08:59:39Z",
                },
            ],
            count: 1,
            remaining: 10,
            total: 30,
        });
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "your_bucket_name" };
        const rawResponseBody = {
            bucket: {
                bucketId: 1,
                created: "2023-10-03T08:59:39Z",
                fileCount: 1,
                fileSize: "3.1GB",
                name: "name",
                updated: "2023-10-03T08:59:39Z",
            },
        };
        server
            .mockEndpoint()
            .post("/v1/bucket")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.buckets.create({
            name: "your_bucket_name",
        });
        expect(response).toEqual({
            bucket: {
                bucketId: 1,
                created: "2023-10-03T08:59:39Z",
                fileCount: 1,
                fileSize: "3.1GB",
                name: "name",
                updated: "2023-10-03T08:59:39Z",
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/bucket")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.buckets.create({
                name: "name",
            });
        }).rejects.toThrow(GroundX.BadRequestError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            bucket: {
                bucketId: 1,
                created: "2023-10-03T08:59:39Z",
                fileCount: 1,
                fileSize: "3.1GB",
                name: "name",
                updated: "2023-10-03T08:59:39Z",
            },
        };
        server.mockEndpoint().get("/v1/bucket/1").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.buckets.get(1);
        expect(response).toEqual({
            bucket: {
                bucketId: 1,
                created: "2023-10-03T08:59:39Z",
                fileCount: 1,
                fileSize: "3.1GB",
                name: "name",
                updated: "2023-10-03T08:59:39Z",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/v1/bucket/1").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.buckets.get(1);
        }).rejects.toThrow(GroundX.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/v1/bucket/1").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.buckets.get(1);
        }).rejects.toThrow(GroundX.UnauthorizedError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { newName: "your_bucket_name" };
        const rawResponseBody = { bucket: { bucketId: 1, name: "name" } };
        server
            .mockEndpoint()
            .put("/v1/bucket/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.buckets.update(1, {
            newName: "your_bucket_name",
        });
        expect(response).toEqual({
            bucket: {
                bucketId: 1,
                name: "name",
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { newName: "newName" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/v1/bucket/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.buckets.update(1, {
                newName: "newName",
            });
        }).rejects.toThrow(GroundX.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { newName: "newName" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/v1/bucket/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.buckets.update(1, {
                newName: "newName",
            });
        }).rejects.toThrow(GroundX.UnauthorizedError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "OK" };
        server.mockEndpoint().delete("/v1/bucket/1").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.buckets.delete(1);
        expect(response).toEqual({
            message: "OK",
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/v1/bucket/1").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.buckets.delete(1);
        }).rejects.toThrow(GroundX.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/v1/bucket/1").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.buckets.delete(1);
        }).rejects.toThrow(GroundX.UnauthorizedError);
    });
});
