// This file was auto-generated by Fern from our API Definition.

import * as GroundX from "../../src/api/index";
import { GroundXClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CustomerClient", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            customer: {
                email: "email",
                first: "first",
                last: "last",
                status: "admin",
                subscription: {
                    billingCycleAnchor: "2024-01-15T09:30:00Z",
                    billingStart: "2024-01-15T09:30:00Z",
                    billingEnd: "2024-01-15T09:30:00Z",
                },
            },
        };

        server.mockEndpoint().get("/v1/customer").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.customer.get();
        expect(response).toEqual(rawResponseBody);
    });

    test("getUsage (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            customer: {
                usage: {
                    metric: "searches",
                    meterId: "mtr_123",
                    value: 4603,
                    startTime: "2026-07-15T00:00:00Z",
                    endTime: "2026-07-29T00:00:00Z",
                    usageAsOf: "2026-07-29T19:20:00Z",
                },
            },
        };

        server.mockEndpoint().get("/v1/customer/usage").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.customer.getUsage({
            metric: "searches",
            startTime: "2026-07-15T00:00:00Z",
            endTime: "2026-07-29T00:00:00Z",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getUsage (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/customer/usage").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.customer.getUsage({
                metric: "searches",
                startTime: "2024-01-15T09:30:00Z",
                endTime: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(GroundX.BadRequestError);
    });

    test("getUsage (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/customer/usage").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.customer.getUsage({
                metric: "searches",
                startTime: "2024-01-15T09:30:00Z",
                endTime: "2024-01-15T09:30:00Z",
            });
        }).rejects.toThrow(GroundX.NotFoundError);
    });
});
