// This file was auto-generated by Fern from our API Definition.

import * as GroundX from "../../src/api/index";
import { GroundXClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("HealthClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            health: { services: [{ lastUpdate: "2023-10-03T08:59:39Z", service: "search", status: "healthy" }] },
        };
        server.mockEndpoint().get("/v1/health").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.health.list();
        expect(response).toEqual({
            health: {
                services: [
                    {
                        lastUpdate: "2023-10-03T08:59:39Z",
                        service: "search",
                        status: "healthy",
                    },
                ],
            },
        });
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            health: { services: [{ lastUpdate: "2023-10-03T08:59:39Z", service: "search", status: "healthy" }] },
        };
        server.mockEndpoint().get("/v1/health/search").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.health.get("search");
        expect(response).toEqual({
            health: {
                services: [
                    {
                        lastUpdate: "2023-10-03T08:59:39Z",
                        service: "search",
                        status: "healthy",
                    },
                ],
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/v1/health/service").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.health.get("service");
        }).rejects.toThrow(GroundX.BadRequestError);
    });
});
