// This file was auto-generated by Fern from our API Definition.

import * as GroundX from "../../src/api/index";
import { GroundXClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SearchClient", () => {
    test("content (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "my search query" };
        const rawResponseBody = {
            search: {
                count: 1,
                results: [{}],
                query: "query",
                score: 1.1,
                searchQuery: "searchQuery",
                text: "text",
                nextToken: "nextToken",
            },
        };
        server
            .mockEndpoint()
            .post("/v1/search/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.search.content(1, {
            n: 1,
            nextToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9",
            verbosity: 1,
            query: "my search query",
        });
        expect(response).toEqual({
            search: {
                count: 1,
                results: [{}],
                query: "query",
                score: 1.1,
                searchQuery: "searchQuery",
                text: "text",
                nextToken: "nextToken",
            },
        });
    });

    test("content (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "my search query" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/search/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.search.content(1, {
                query: "my search query",
            });
        }).rejects.toThrow(GroundX.BadRequestError);
    });

    test("content (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "my search query" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/search/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.search.content(1, {
                query: "my search query",
            });
        }).rejects.toThrow(GroundX.UnauthorizedError);
    });

    test("documents (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "my search query", documentIds: ["docUUID1", "docUUID2"] };
        const rawResponseBody = {
            search: {
                count: 1,
                results: [{}],
                query: "query",
                score: 1.1,
                searchQuery: "searchQuery",
                text: "text",
                nextToken: "nextToken",
            },
        };
        server
            .mockEndpoint()
            .post("/v1/search/documents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.search.documents({
            n: 1,
            nextToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9",
            verbosity: 1,
            query: "my search query",
            documentIds: ["docUUID1", "docUUID2"],
        });
        expect(response).toEqual({
            search: {
                count: 1,
                results: [{}],
                query: "query",
                score: 1.1,
                searchQuery: "searchQuery",
                text: "text",
                nextToken: "nextToken",
            },
        });
    });

    test("documents (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "my search query", documentIds: ["documentIds", "documentIds"] };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/search/documents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.search.documents({
                query: "my search query",
                documentIds: ["documentIds", "documentIds"],
            });
        }).rejects.toThrow(GroundX.BadRequestError);
    });

    test("documents (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "my search query", documentIds: ["documentIds", "documentIds"] };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/search/documents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.search.documents({
                query: "my search query",
                documentIds: ["documentIds", "documentIds"],
            });
        }).rejects.toThrow(GroundX.UnauthorizedError);
    });
});
