// This file was auto-generated by Fern from our API Definition.

import { GroundXClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Workflows", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            workflows: [
                {
                    chunkStrategy: "element",
                    documentId: "documentId",
                    id: 1,
                    name: "name",
                    extract: { key: "value" },
                    sectionStrategy: "chunks",
                    workflowId: "workflowId",
                },
            ],
        };
        server.mockEndpoint().get("/v1/workflow").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.workflows.list();
        expect(response).toEqual({
            workflows: [
                {
                    chunkStrategy: "element",
                    documentId: "documentId",
                    id: 1,
                    name: "name",
                    extract: {
                        key: "value",
                    },
                    sectionStrategy: "chunks",
                    workflowId: "workflowId",
                },
            ],
        });
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            workflow: {
                chunkStrategy: "element",
                documentId: "documentId",
                id: 1,
                name: "name",
                extract: { key: "value" },
                sectionStrategy: "chunks",
                relationships: { account: true, documents: ["documents"], ids: [1] },
                workflowId: "workflowId",
            },
        };
        server
            .mockEndpoint()
            .post("/v1/workflow")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.create({});
        expect(response).toEqual({
            workflow: {
                chunkStrategy: "element",
                documentId: "documentId",
                id: 1,
                name: "name",
                extract: {
                    key: "value",
                },
                sectionStrategy: "chunks",
                relationships: {
                    account: true,
                    documents: ["documents"],
                    ids: [1],
                },
                workflowId: "workflowId",
            },
        });
    });

    test("getAccount", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            workflow: {
                chunkStrategy: "element",
                documentId: "documentId",
                id: 1,
                name: "name",
                extract: { key: "value" },
                sectionStrategy: "chunks",
                relationships: { account: true, documents: ["documents"], ids: [1] },
                workflowId: "workflowId",
            },
        };
        server
            .mockEndpoint()
            .get("/v1/workflow/relationship")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.getAccount();
        expect(response).toEqual({
            workflow: {
                chunkStrategy: "element",
                documentId: "documentId",
                id: 1,
                name: "name",
                extract: {
                    key: "value",
                },
                sectionStrategy: "chunks",
                relationships: {
                    account: true,
                    documents: ["documents"],
                    ids: [1],
                },
                workflowId: "workflowId",
            },
        });
    });

    test("addToAccount", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { workflowId: "workflowId" };
        const rawResponseBody = { message: "OK" };
        server
            .mockEndpoint()
            .post("/v1/workflow/relationship")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.addToAccount({
            workflowId: "workflowId",
        });
        expect(response).toEqual({
            message: "OK",
        });
    });

    test("removeFromAccount", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "OK" };
        server
            .mockEndpoint()
            .delete("/v1/workflow/relationship")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.removeFromAccount();
        expect(response).toEqual({
            message: "OK",
        });
    });

    test("addToId", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { workflowId: "workflowId" };
        const rawResponseBody = { message: "OK" };
        server
            .mockEndpoint()
            .post("/v1/workflow/relationship/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.addToId(1, {
            workflowId: "workflowId",
        });
        expect(response).toEqual({
            message: "OK",
        });
    });

    test("removeFromId", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "OK" };
        server
            .mockEndpoint()
            .delete("/v1/workflow/relationship/1")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.removeFromId(1);
        expect(response).toEqual({
            message: "OK",
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            workflow: {
                chunkStrategy: "element",
                documentId: "documentId",
                id: 1,
                name: "name",
                extract: { key: "value" },
                sectionStrategy: "chunks",
                relationships: { account: true, documents: ["documents"], ids: [1] },
                workflowId: "workflowId",
            },
        };
        server.mockEndpoint().get("/v1/workflow/1").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.workflows.get(1);
        expect(response).toEqual({
            workflow: {
                chunkStrategy: "element",
                documentId: "documentId",
                id: 1,
                name: "name",
                extract: {
                    key: "value",
                },
                sectionStrategy: "chunks",
                relationships: {
                    account: true,
                    documents: ["documents"],
                    ids: [1],
                },
                workflowId: "workflowId",
            },
        });
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            workflow: {
                chunkStrategy: "element",
                documentId: "documentId",
                id: 1,
                name: "name",
                extract: { key: "value" },
                sectionStrategy: "chunks",
                relationships: { account: true, documents: ["documents"], ids: [1] },
                workflowId: "workflowId",
            },
        };
        server
            .mockEndpoint()
            .put("/v1/workflow/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.update("id", {});
        expect(response).toEqual({
            workflow: {
                chunkStrategy: "element",
                documentId: "documentId",
                id: 1,
                name: "name",
                extract: {
                    key: "value",
                },
                sectionStrategy: "chunks",
                relationships: {
                    account: true,
                    documents: ["documents"],
                    ids: [1],
                },
                workflowId: "workflowId",
            },
        });
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new GroundXClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "OK" };
        server.mockEndpoint().delete("/v1/workflow/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.workflows.delete("id");
        expect(response).toEqual({
            message: "OK",
        });
    });
});
