/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../../../../index.js";

/**
 * @example
 *     {
 *         workflowId: "workflowId"
 *     }
 */
export interface WorkflowUpdateRequest {
    /** The name of the workflow being created. */
    name?: string;
    steps?: GroundX.WorkflowSteps;
    /** The id of the workflow that is being updated. */
    workflowId: string;
}
