// This file was auto-generated by Fern from our API Definition.

import { BucketsClient } from "./api/resources/buckets/client/Client.js";
import { CustomerClient } from "./api/resources/customer/client/Client.js";
import { DocumentsClient } from "./api/resources/documents/client/Client.js";
import { GroupsClient } from "./api/resources/groups/client/Client.js";
import { HealthClient } from "./api/resources/health/client/Client.js";
import { McpClient } from "./api/resources/mcp/client/Client.js";
import { SearchClient } from "./api/resources/search/client/Client.js";
import { WorkflowsClient } from "./api/resources/workflows/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace GroundXClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class GroundXClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<GroundXClient.Options>;
    protected _mcp: McpClient | undefined;
    protected _documents: DocumentsClient | undefined;
    protected _search: SearchClient | undefined;
    protected _buckets: BucketsClient | undefined;
    protected _groups: GroupsClient | undefined;
    protected _workflows: WorkflowsClient | undefined;
    protected _customer: CustomerClient | undefined;
    protected _health: HealthClient | undefined;

    constructor(options: GroundXClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get mcp(): McpClient {
        return (this._mcp ??= new McpClient(this._options));
    }

    public get documents(): DocumentsClient {
        return (this._documents ??= new DocumentsClient(this._options));
    }

    public get search(): SearchClient {
        return (this._search ??= new SearchClient(this._options));
    }

    public get buckets(): BucketsClient {
        return (this._buckets ??= new BucketsClient(this._options));
    }

    public get groups(): GroupsClient {
        return (this._groups ??= new GroupsClient(this._options));
    }

    public get workflows(): WorkflowsClient {
        return (this._workflows ??= new WorkflowsClient(this._options));
    }

    public get customer(): CustomerClient {
        return (this._customer ??= new CustomerClient(this._options));
    }

    public get health(): HealthClient {
        return (this._health ??= new HealthClient(this._options));
    }
}
