/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Documents } from "./api/resources/documents/client/Client";
import { Search } from "./api/resources/search/client/Client";
import { Buckets } from "./api/resources/buckets/client/Client";
import { Groups } from "./api/resources/groups/client/Client";
import { Customer } from "./api/resources/customer/client/Client";
import { Health } from "./api/resources/health/client/Client";

export declare namespace GroundXClient {
    interface Options {
        environment?: core.Supplier<environments.GroundXEnvironment | string>;
        apiKey: core.Supplier<string>;
        fetcher?: core.FetchFunction;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class GroundXClient {
    protected _documents: Documents | undefined;
    protected _search: Search | undefined;
    protected _buckets: Buckets | undefined;
    protected _groups: Groups | undefined;
    protected _customer: Customer | undefined;
    protected _health: Health | undefined;

    constructor(protected readonly _options: GroundXClient.Options) {}

    public get documents(): Documents {
        return (this._documents ??= new Documents(this._options));
    }

    public get search(): Search {
        return (this._search ??= new Search(this._options));
    }

    public get buckets(): Buckets {
        return (this._buckets ??= new Buckets(this._options));
    }

    public get groups(): Groups {
        return (this._groups ??= new Groups(this._options));
    }

    public get customer(): Customer {
        return (this._customer ??= new Customer(this._options));
    }

    public get health(): Health {
        return (this._health ??= new Health(this._options));
    }
}
