// This file was auto-generated by Fern from our API Definition.

export const GroundXEnvironment = {
    Default: "https://api.groundx.ai/api",
} as const;

export type GroundXEnvironment = typeof GroundXEnvironment.Default;
