// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         newName: "your_bucket_name"
 *     }
 */
export interface BucketUpdateRequest {
    /** The new name of the bucket being renamed. */
    newName: string;
}
