/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../../../../index.js";

/**
 * @example
 *     {
 *         n: 1,
 *         status: "queued"
 *     }
 */
export interface DocumentsGetProcessesRequest {
    /**
     * The maximum number of returned processes. Accepts 1-100 with a default of 20.
     */
    n?: number;
    /**
     * A status filter on the processing status. If this value is set, then only processes with this status will be returned in the results.
     */
    status?: GroundX.ProcessingStatus;
}
