/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../../../../index";

/**
 * @example
 *     {
 *         files: [{
 *                 bucketId: 1234,
 *                 fileData: "binary data here",
 *                 fileName: "my_file.txt",
 *                 fileType: "txt"
 *             }]
 *     }
 */
export interface DocumentLocalIngestRequest {
    files: GroundX.IngestLocalDocument[];
}
