// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         toBucket: 1234
 *     }
 */
export interface DocumentCopyRequest {
    /** The document IDs of the files you wish to copy. */
    documentIds?: string[];
    /** The bucketId of the bucket you wish to copy ALL files from. */
    fromBucket?: number;
    /** The bucketId of the bucket the file will be copied into. */
    toBucket: number;
}
