// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../../../../index.js";

/**
 * @example
 *     {
 *         documents: [{
 *                 documentId: "documentId"
 *             }]
 *     }
 */
export interface DocumentUpdateRequest {
    documents: GroundX.DocumentUpdate[];
    /** An endpoint that will receive processing event updates as POST. */
    callbackUrl?: string;
    /** A string that is returned, along with processing event updates, to the callback URL. */
    callbackData?: string;
}
