// This file was auto-generated by Fern from our API Definition.

import type * as GroundX from "../../../../index.js";

/**
 * @example
 *     {
 *         documents: [{
 *                 bucketId: 1234,
 *                 fileName: "my_file1.txt",
 *                 fileType: "txt",
 *                 sourceUrl: "https://my.source.url.com/file1.txt"
 *             }]
 *     }
 */
export interface DocumentRemoteIngestRequest {
    documents: GroundX.IngestRemoteDocument[];
    /** An endpoint that will receive processing event updates as POST. */
    callbackUrl?: string;
    /** A string that is returned, along with processing event updates, to the callback URL. */
    callbackData?: string;
}
