/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../../../../index";

/**
 * @example
 *     {
 *         websites: [{
 *                 bucketId: 1234,
 *                 cap: 100,
 *                 depth: 3,
 *                 searchData: {
 *                     "key": "value"
 *                 },
 *                 sourceUrl: "https://my.website.com"
 *             }]
 *     }
 */
export interface WebsiteCrawlRequest {
    websites: GroundX.WebsiteSource[];
}
