/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../../../../index.js";

/**
 * @example
 *     {
 *         websites: [{
 *                 bucketId: 1234,
 *                 cap: 10,
 *                 depth: 2,
 *                 searchData: {
 *                     "key": "value"
 *                 },
 *                 sourceUrl: "https://my.website.com"
 *             }]
 *     }
 */
export interface WebsiteCrawlRequest {
    websites: GroundX.WebsiteSource[];
    /** The URL that will receive processing event updates. */
    callbackUrl?: string;
    /** A string that is returned, along with processing event updates, to the callback URL. */
    callbackData?: string;
}
