/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as GroundX from "../../../../index";

/**
 * @example
 *     {
 *         websites: [{
 *                 bucketId: 123,
 *                 sourceUrl: "https://my.website.com"
 *             }]
 *     }
 */
export interface WebsiteCrawlRequest {
    websites: GroundX.WebsiteCrawlRequestWebsitesItem[];
}
